### ISSUE TITLE
draw.io Alternative Frontend Editor

### ISSUE THREAD

**Issue by curtisma** [Vlsir/Hdl21Schematics#30]
Cool project, thanks for the great work!

I had considered doing something similar using [diagrams.net](https://app.diagrams.net/) (aka draw.io)  which also has a VS code extension, a desktop electron app, and a web app.  It also has some built-in circuit symbols that look good. (you just need to enable them)

The draw.io program works great and I started using it as an improvement over Microsoft Visio.  It has a great UI which is easy to use.  The native save format is an XML file and the blocks can have properties attached to them.  It could be considered as an alternative editor in the future.

However, I do really like the portability of viewing SVG images that Hdl21Schematics provides.  The draw.io has a bunch of great export formats including svg and html. It isn't quite as easy as viewing the source directly, but it is close.

**Comment by dan-fritchman** [comment]
Love draw.io. I have used them for years, for drawing all kinds of block diagrams, documentation, other such figures. 

The core function of the schematic editor does two things though: 
1. Draw pictures
2. Comprehend them as circuits
All of the general-purpose vector-image editors - draw.io, OmniGraffle (the GOAT), Visio, Inskscape, etc - do a great job of #1. Better than our custom tool does by aways. But they don't - and I don't see how they could - cover #2. 

If one or more of these pieces of software had some extension system, both to the editor application(s) and to their format, and that was sufficiently easy to use, and the format remained easily renderable (i.e. without their custom software), and one had the trust that all these features wouldn't go away - I'd be all ears. Do any have such things? (Honest question, I don't know of one.) 

That whole paragraph is, in large part, the motivation for SVG: there's no custom software, no custom web server, no app, no anything special needed to **read** SVG. Therefore there's no such software required to read schematics. And perhaps the counter-intuitive part is: **schematics are read-mostly**. Even when "working on" them, much or most of the time is spent.. just looking at them. When you move to use-cases like sharing, across a team and even moreso across an institution, that share of "read %" quickly goes to 100%.
